### ISSUE TITLE
`.flynn20` is written twice

### ISSUE THREAD

**Issue by yurkagon** [chriscareycode/doom-flynn-css#1]
Hi, I use your icon in my mini-game :)
You asked someone to let you know if it is used somewhere, so here: 
https://github.com/yurkagon/Doom-Nukem-CSS
https://yurkagon.github.io/Doom-Nukem-CSS/

Also I found that small issue :)
```
.flynn20 {background-position:0px -1216px;}
.flynn20 {background-position:0px -1280px;}
```

**Comment by chriscareycode** [comment]
Thank you for this report. This has been fixed.

**Comment by chriscareycode** [comment]
@yurkagon  Cool game! This is great to see in the browser. I'll check it out in more detail when I get home.

**Comment by yurkagon** [comment]
@chriscareycode  Thanks :)

Let me know when you check it :)
